# Generated by Django 4.2.14 on 2024-08-16 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TuliusCookBook', '0007_alter_comment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название страны')),
                ('info', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='О стране')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='country/')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='CountryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('ingredient', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Ингридиенты')),
                ('recipe_text', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст рецепта')),
                ('about', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='О блюде')),
                ('description', models.TextField(verbose_name='Краткая информация')),
                ('foto', models.CharField(max_length=1024, verbose_name='Ссылка на фото')),
                ('time_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Country.country')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TuliusCookBook.section')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='CountryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('time_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Country.countryreceipt')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['title'], name='Country_cou_title_f4482c_idx'),
        ),
        migrations.AddIndex(
            model_name='countryreceipt',
            index=models.Index(fields=['name'], name='Country_cou_name_7b1988_idx'),
        ),
    ]
