# Generated by Django 4.2.14 on 2024-07-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Аннотация')),
                ('link_to_story', models.CharField(max_length=512, null=True, verbose_name='Ссылка на сюжет')),
                ('link_to_image', models.CharField(max_length=512, null=True, verbose_name='Ссылка на карту')),
            ],
            options={
                'verbose_name': 'Сюжет',
                'verbose_name_plural': 'Сюжеты',
            },
        ),
    ]
