# Generated by Django 4.2.14 on 2024-08-01 09:12

import TuliusCookBook.models
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TuliusCookBook', '0002_profile_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('time_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=128, verbose_name='Название блюда')),
                ('ingredient', models.TextField(verbose_name='Ингридиенты')),
                ('recipe_text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст рецепта')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание рецепта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[TuliusCookBook.models.Recipe.validate_image])),
                ('time_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='signature',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Подпись'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['nikname'], name='TuliusCookB_nikname_d6c1f6_idx'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TuliusCookBook.profile'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TuliusCookBook.section'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TuliusCookBook.catalogstories'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TuliusCookBook.profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TuliusCookBook.recipe'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['dish_name'], name='TuliusCookB_dish_na_a6ec30_idx'),
        ),
    ]
