# Generated by Django 4.2.14 on 2024-08-09 08:35

import TuliusCookBook.models
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TuliusCookBook', '0003_comment_recipe_alter_profile_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receipt/', validators=[TuliusCookBook.models.Recipe.validate_image]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Ингридиенты'),
        ),
    ]
