# Generated by Django 4.2.14 on 2024-08-12 10:56

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TuliusCookBook', '0005_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Ингридиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст рецепта'),
        ),
    ]
